version: "3.9"

services:
  backend:
    build: .
    command: gunicorn lms_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A lms_project worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - backend
      - redis

  celery_beat:
    build: .
    command: celery -A lms_project beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - backend
      - redis

volumes:
  postgres_data:
