name: CI/CD

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: pip install poetry

      - name: Configure Poetry (no venv inside project)
        run: poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run migrations (check DB setup)
        run: poetry run python manage.py makemigrations --check --dry-run

      - name: Run tests
        run: poetry run python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/develop'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /var/www/your_project
            git fetch --all
            git reset --hard origin/develop
            docker-compose pull
            docker-compose up -d --build .
