# Generated by Django 5.2.5 on 2025-08-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_remove_course_created_at_remove_lesson_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='currency',
            field=models.CharField(default='usd', help_text='Валюта для Stripe (usd, eur и т.д.)', max_length=3),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Цена курса в валюте проекта', max_digits=10),
        ),
    ]
