name: CI/CD

on:
  push:
    branches:
      - homework-deploy
      - main
  pull_request:
    branches:
      - homework-deploy
  workflow_dispatch:

jobs:
  test:
    name: Test & Migrate
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test_user -d test_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v4

      # Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Кэш pip
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Установка зависимостей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Проверяем, что PostgreSQL доступен
      - name: Wait for Postgres
        run: |
          until pg_isready -h 127.0.0.1 -p 5432 -U test_user; do
            echo "Waiting for postgres..."
            sleep 2
          done

      # Применяем миграции
      - name: Apply migrations
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_PORT: 5432
        run: |
          python manage.py migrate --noinput

      # Запуск тестов
      - name: Run tests
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_PORT: 5432
          REDIS_URL: redis://127.0.0.1:6379/0
        run: |
          pip install pytest
          pytest -q
